language: python
python: 3.8
cache: pip

before_install:
- pip install -r requirements.txt

jobs:
  include:
  - stage: "Lint"
    script:
      - pylint --rcfile=.pylintrc ./collector/ --init-hook='sys.path.extend(["./collector/"])'

branches:
  only:
  - master
